# Data Wrangling the Mathematics Genealogy Project and MathSciNet data

#### Scott Atkinson

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time


pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
# data_list = [pd.read_csv('MGP/MGP%s,%s.csv'%(K*1000 + 1, (K+1)*1000+1)) for K in range(0,265)] + [pd.read_csv('MGP/MGP_missed.csv')]

# df = pd.concat(data_list,ignore_index=True)

# df.to_csv('MGP/MGP_scrape.csv')

In [3]:
df = pd.read_csv('MGP/MGP_scrape.csv', index_col = 'MGP_ID')

In [4]:
df.shape

(259553, 9)

In [5]:
df.head()

Unnamed: 0  Unnamed: 0.1                        Name  \
MGP_ID                                                         
1                0             0  \nErnest Willard Anderson    
2                1             1           \nArchie  Higdon    
3                2             2         \nDonald Hill Rock    
4                3             3    \nCharles Joseph Thorne    
5                4             4        \nRalph Harry Tripp    

                                                                                                                                                                                                                                                                                                                                                                    Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                            
1       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1933</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
2       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1936</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
3       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1939</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
4       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1941</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
5       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1942</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   

                                                                                         Thesis  \
MGP_ID                                                                                            
1             \n\nStatics of Special Types of Homogeneous Elastic Slabs with Variable Thickness   
2                                           \n\nStresses in Moderately Thick Rectangular Plates   
3                                                  \n\nFinite Strain Analysis in Elastic Theory   
4       \n\nThe Approximate Solution of Linear Differential Equations by the Use of Functionals   
5                                     \n\nStatical Equilibrium of Skew and Sector-Shaped Plates   

                                                                          MSC  \
MGP_ID                                                                          
1       Mathematics Subject Classification: 74—Mechanics of deformable solids   
2       Mathematics Subj

In [6]:
# drop unnecessary columns

df.drop(['Unnamed: 0','Unnamed: 0.1'], inplace = True, axis = 1)

In [7]:
# list of records to drop because they are true duplicates

drop_list = [243871, 
             251053, 
             219211, 
             253054, 
             261290, 
             240314, 
             248056,
             249634,
             210665,
             228171,
             234621,
             123111,
             253044,
             229095,
             206046,
             251433,
             216883,
             245041,
             257139,
             98019,
             260878,
             209542,
             221267,
             255265,
             254011,
             260874,
             231864,
             233120,
             251395,
             258014,
             251069,
             260877,
             261279,
             251816,
             242126,
             243844,
             263123,
             261189,
             260241,
             168951,
             223969,
             197269,
             173422,
             63638,
             199123,
             238993,
             238113,
             242960,
             134258,
             253326,
             207214,
             232090,
             231387,
             245248,
             215101,
             240249,
             106754,
             243236,
             233534,
             70269,
             237125,
             198385,
             241592,
             124495,
             239939,
             112397,
             233540,
             26727,
             257835,
             226455,
             244763,
             206698,
             239483,
             207383,
             239384,
             257999,
             252342,
             200574,
             206048,
             189464,
             233486,
             185355,
             246884,
             203076,
             122375,
             252389,
             245255
            ]

df.drop(drop_list, inplace=True)

In [8]:
df[df.duplicated(keep=False)].sort_values('Name').shape

(84, 7)

In [9]:
df.shape

(259466, 7)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.shape

(259423, 7)

## Cleaning Thesis column

In [12]:



# remove \n from thesis column

df['Thesis'] = df['Thesis'].str.strip('\n')

In [13]:
df.columns

Index(['Name', 'Degree_Info', 'Thesis', 'MSC', 'Advisor', 'Descendants',
       'MScNID'],
      dtype='object')

## Extracting degree title, school, and country data from degree info column

In [14]:
# functions to extract degree title, institutions name, and country

def extract_deg(x):
    return '%s' %(x.split('margin-right: 0.5em">')[-1].split('<span')[0])
def extract_school(x):
    return '%s' %(x.split('margin-left: 0.5em">')[-1].split('</span')[0])
def extract_country(x):
    return '%s' %(x.split('title="')[-1].split('"')[0])

In [15]:
df['Degree'] = df['Degree_Info'].apply(extract_deg)
df['School'] = df['Degree_Info'].apply(extract_school)
df['Country'] = df['Degree_Info'].apply(extract_country)

In [16]:
# cleaning up country column

df[df['Country'].str.contains('div')]

Name  \
MGP_ID                        
238        \nGeorge  Reese    
247     \nRajbir S. Dahiya    
253       \nMaple  Hartley    
271         \nG.  Nariboli    
272      \nMichael  Barber    
...                     ...   
264130   \nHannes  Krasser    
264132     \nMartin  Balko    
264137     \nGui-Zhang  Tu    
264138        \nKang  Feng    
264142  \nShigeki  Akiyama    

                                                                                                                                                                                             Degree_Info  \
MGP_ID                                                                                                                                                                                                     
238     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> 2002</span>\n</div>   
247         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
253         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
271         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
272         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
...                                                                                                                                                                                                  ...   
264130  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> 2003</span>\n</div>   
264132  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> 2016</span>\n</div>   
264137           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
264138           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   
264142           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   

                                                                                                                                                                                         Thesis  \
MGP_ID                                                                                                                                                                                            
238     Technology-enhanced Education Reform: An Historical Analysis of the Evolution of the office for Mathematics, Science and Technology Education at the University of Illinois (1993-2002)   
247                                                                                                                                                                                               
253                                                                                                                                                                                       

In [17]:
# Convert '<div style=' to 'Unknown' in 'Country' column

df['Country'] = df['Country'].apply(lambda C: 'Unknown' if C == '<div style=' else C)

In [18]:
# a function to determine the number of time </span> shows up in a value

def split_length(s):
    return len(s.split('</span>'))

## Extracting year data

In [19]:
df[df['Degree_Info'].apply(split_length) < 3].shape

(2, 10)

2 rows have `'</span>'` show up less than twice in the `'Degree_Info'` column

In [20]:
def extract_year(x):
    if len(x.split('</span>')) > 2:
        return '%s' %(x.split('margin-left: 0.5em">')[-1].split('</span>')[1].split('</'))[0]
    else:
        return 0
df['Year'] = df['Degree_Info'].apply(extract_year)

In [21]:
# convert all year values to strings to for cleaning

df['Year'] = df['Year'].apply(str)

In [22]:
df['Year'] = df['Year'].str.strip(' ')

In [23]:
# convert all empty years to 0 so we can make this column type integers
df['Year'] = df['Year'].apply(lambda C: '0' if C == '' else C)

In [24]:
df[~df['Year'].str[:4].str.isdigit()]

Name  \
MGP_ID                        
73629    \nJoseph  Dienger    
248564  \nMahdi  Safinejad    

                                                                                                                                                                                                                                                                                                                                                                                Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                        
73629   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Dr. phil. <span style="color:\n  #006633; margin-left: 0.5em">Karlsruher Institut für Technologie (KIT)</span> c. 1845</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
248564  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Graduate University of Advanced Technology of Kerman</span> Aug. 2018</span>\n<img alt="Iran" height="30" src="img/flags/Iran.gif" style="border: 0; vertical-align: middle" title="Iran" width="52"/>\n</div>   

                                                                                                            Thesis  \
MGP_ID                                                                                                               
73629                                                                                                                
248564  Meshless Methods Based On The Radial Basis Functions For Solving Fractional Integro-Differential Equations   

                                                                 MSC  \
MGP_ID                                                                 
73629   Mathematics Subject Classification: 53—Differential geometry   
248564                                                  No MSC given   

                                                                                                                                                                                            Advisor  \
MGP_ID                                                                                                                                                                                                
73629                                                                                                                                                                                          None   
248564  <p style="text-align: center; line-height: 2.75ex">Advisor 1: <a href="id.php?id=15475">Mahmoud  Mohseni Moghadam</a><br/>Advisor 2: <a href="id.php?id=248565">Ahmad  Shirazi</a><br/></p>   

               Descendants  \
MGP_ID                       
73629   No students known.   
248564  No students known.   

                                                                                           MScNID  \
MGP_ID                                                                                              
73629   <p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small">\n</p>   
248564  <p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small">\n</p>   

            Degree                                                School  \
MGP_ID                                                                     
73629   Dr. phil.              Karlsruher Institut für Technologie (KIT)   
248564      Ph.D.   Graduate University of Advanced 

In [25]:
df.loc[73629,['Year']] = '1845'

In [26]:
df.loc[248564, ['Year']] = '2018'

In [27]:
df[~(df['Year'].str.isdigit()) & (df['Year'].str[:4].str.isdigit())]

Name  \
MGP_ID                                    
7824                  \nArthur  Cayley    
13720                   \nPaul  Ledoux    
19988                 \nSvante  Janson    
20783               \nPavel  Kleinmann    
23816                \n  Lê Dũng Tráng    
...                                 ...   
132044              \nJohannes  Calvin    
132507             \nPieter  Nieuwland    
133595  \nEduard Hendrik von Baumhauer    
134896                \nLucas  Schacht    
234545                  \nJames  Pound    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
7824    <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. / Ph.D. / Dr Sc. <span style="color:\n  #006633; margin-left: 0.5em">Universiteit Leiden and University College Dublin and University of Oxford</span> 1864/1865/1875</span>\n<img alt="Netherlands" height="30" src="img/flags/Netherlands.gif" style="border: 0; vertical-align: middle" title="Netherlands" width="45"/>\n<img alt="Ireland" height="30" src="img/flags/Ireland.gif" style="border: 0; vertical-align: middle" title="Ireland" width="60"/>\n<img alt="UnitedKingdom" height="30" src="img/flags/UnitedKingdom.gif" style="border: 0; vertical-align: middle" title="UnitedKingdom" width="60"/>\n</div>   
13720                                                                                                                                                                                                                                                                                                                                                                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Doctorat en Sciences <span style="color:\n  #006633; margin-left: 0.5em">Université de Liège</span> 1946 / 1949</span>\n<img alt="Belgium" height="30" src="img/flags/Belgium.gif" style="border: 0; vertical-align: middle" title="Belgium" width="35"/>\n</div>   
19988                                                                                                                                                                                                                                                                                                                                                                                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Uppsala Universite

In [28]:
def earlier_year(s):
    if not s.isdigit() and s[:4].isdigit():
        return s[:4]
    else:
        return s
        

In [29]:
# take earlier year listed

df['Year'] = df['Year'].apply(earlier_year)

In [30]:
# based on thesis info, ID#41944 earned her PhD in 1882

df.loc[41944, ['Year']] = '1882'

In [31]:
df.loc[111235, 'Year']

'1998'

In [32]:
# some strange formatting for ID#111235, set year to 1998

df.loc[111235, 'Year'] = '1998'

In [33]:
df[(df['Year'].str.isdigit())]

Name  \
MGP_ID                               
1       \nErnest Willard Anderson    
2                \nArchie  Higdon    
3              \nDonald Hill Rock    
4         \nCharles Joseph Thorne    
5             \nRalph Harry Tripp    
...                            ...   
64700      \nEugene Myron Barston    
64693            \nKai-Jaung  Pei    
64714         \nMarek W. Kaminski    
182835           \nDaniel  Seidel    
182843            \nRobert  Benim    

                                                                                                                                                                                                                                                                                                                                                                                      Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                              
1                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1933</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
2                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1936</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
3                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1939</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
4                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1941</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
5                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1942</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                           ...   
64700                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Stanford University</span> 1964</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
64693         <div style="line-hei

In [34]:
df[df['Year'].str.contains('c')]

Empty DataFrame
Columns: [Name, Degree_Info, Thesis, MSC, Advisor, Descendants, MScNID, Degree, School, Country, Year]
Index: []

In [35]:
# all 'Year' values are integers, convert back to integers
df['Year'] = df['Year'].apply(int)

In [36]:
# sort by year to find weird year values

df[df['Year']>0].sort_values('Year', ascending = False)

Name  \
MGP_ID                              
235671             \nKai  Kopfer    
252420          \nIrene Y. Zhang    
238848              \nErfang  Ma    
254349           \nTuan Anh  Dao    
260624         \nAnna  Quaglieri    
...                           ...   
184631    \nTheodore  Metochites    
201288     \nGregory  Chioniadis    
261324           \nJaimee  Brown    
254024  \nMohammad Esmael  Samei    
259778     \nPedro Toniol Cardin    

                                                                                                                                                                                                                                                                                                                                                                                   Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                           
235671               <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Ruprecht-Karls-Universität Heidelberg</span> 20018</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
252420              <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Washington</span> 2107</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
238848                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Otago</span> 2102</span>\n<img alt="NewZealand" height="30" src="img/flags/NewZealand.gif" style="border: 0; vertical-align: middle" title="NewZealand" width="60"/>\n</div>   
254349                                     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Uppsala Universitet</span> 2024</span>\n<img alt="Sweden" height="30" src="img/flags/Sweden.gif" style="border: 0; vertical-align: middle" title="Sweden" width="48"/>\n</div>   
260624                        <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Melbourne</span> 2020</span>\n<img alt="Australia" height="30" src="img/flags/Australia.gif" style="border: 0; vertical-align: middle" title="Australia" width="60"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                        ...   
184631                                                                                                                                                                                             <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> 1315</span>\n</div>   
201288                                            <div style="line-height

IDs 235671, 252420, 238848 need correcting

In [37]:
# sort by year to find weird year values

df[df['Year']>0].sort_values('Year').head(20)

Name  \
MGP_ID                                        
259778               \nPedro Toniol Cardin    
254024            \nMohammad Esmael  Samei    
261324                     \nJaimee  Brown    
201288               \nGregory  Chioniadis    
184631              \nTheodore  Metochites    
127264         \nHeinrich  von Langenstein    
146365                  \nNilos  Kabasilas    
131575         \nGeorgios Plethon Gemistos    
127737  \nJohann  Hoffmann von Schweidnitz    
126887             \nJohannes  von Gmunden    
134931                \nGuarino  da Verona    
134873              \nVittorino  da Feltre    
133754         \nTheodoros II  Palaiologos    
131584                  \nTheodoros  Gazes    
131561               \nBasilios  Bessarion    
126087              \nGeorg  von Peuerbach    
131444            \nJohannes  Argyropoulos    
127166                \nNiccolò  Leoniceno    
131576         \nDemetrios  Chalcocondyles    
126109     \nJohannes Müller Regiomontanus    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
259778                                                                                                                                    <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Universidade Estadual Paulista "Júlio de Mesquita Filho"</span> 20</span>\n<img alt="Brazil" height="30" src="img/flags/Brazil.gif" style="border: 0; vertical-align: middle" title="Brazil" width="43"/>\n</div>   
254024                                                                                                                                                                                                                                                                                                                            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> 43</span>\n</div>   
261324                                                                                                                                               <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Queensland University of Technology</span> 200</span>\n<img alt="Australia" height="30" src="img/flags/Australia.gif" style="border: 0; vertical-align: middle" title="Australia" width="60"/>\n</div>   
201288                                                                                                                                                                              <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em">Ilkhans Court at Tabriz</span> 1296</span>\n<img alt="Iran" height="30" src="img/fla

IDs 259778, 254024, 261324 have incorrect years

In [38]:
# fixing it

df.loc[235671, 'Year'] = 2018
df.loc[252420, 'Year'] = 2017
df.loc[238848, 'Year'] = 2012
df.loc[261324, 'Year'] = 2007
df.loc[254024, 'Year'] = 2013
df.loc[259778, 'Year'] = 2011

In [39]:
# ID 254349 has a future degree year, and we are only interested in current PhDs
df.drop(254349, inplace=True)

In [40]:
df[df['Year'] >0].sort_values('Year', ascending = False).head(30)

Name  \
MGP_ID                                   
263093             \nGurjit  Randhawa    
262876                \nLong Louis Ly    
259917              \nHenning  Schatz    
258809                    \nXin  Tang    
261561               \nOusmane  Kodio    
258807  \nJeya Balaji Balasubramanian    
258806            \nPrachi  Loliencar    
258805              \nGeorgia  Ellina    
262877                 \nHieu  Nguyen    
262804              \nAhlam  Almulhim    
262880                    \nThu  Dinh    
262881             \nMelissa  McGuirl    
262882              \nXiaoying  Zhang    
262883             \nKellen  Petersen    
262884                     \nHan  Liu    
261554              \nBrian  de Silva    
262839             \nMallory  McMahon    
258811            \nAndrés  Contreras    
262836                  \nYubai  Yuan    
261563        \nSeyed Mohssen Ghafari    
261565          \nBoutheina  Nemouchi    
262831                     \nSimo  Wu    
262830             \nKjetil Olsen Lye    
262829              \nMaxim  Gerspach    
262828        \nDaniel Agoston Bálint    
262827             \nStephan  Artmann    
261567              \nGiuliano  Basso    
262822                    \nMeng  Cao    
262821            \nChristopher  Ryba    
262820             \nHisham  Alasmary    

                                                                                                                                                                                                                                                                                                                                                                                         Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                 
263093                                 <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Western Ontario</span> 2020</span>\n<img alt="Canada" height="30" src="img/flags/Canada.gif" style="border: 0; vertical-align: middle" title="Canada" width="60"/>\n</div>   
262876               <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Texas at Austin</span> 2020</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
259917                                 <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Dr. rer. nat. <span style="color:\n  #006633; margin-left: 0.5em">Universität Kassel</span> 2020</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
258809                                                                                                                                                                                              <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em"></span> 2020</span>\n</div>   
261561                     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Oxford</span> 2020</span>\n<img alt="UnitedKingdom" height="30" src="img/flags/UnitedKingdom.gif" style="border: 0; vertical-align:

## Getting MSC number

Isolating the MSC number:

In [41]:
def extract_msc(x):
    if x != 'No MSC given':
        return '%s' %(x.split(': ')[-1].split('—')[0])
    else:
        return np.nan



In [42]:
df['msc'] = df['MSC'].apply(extract_msc)

## Extracting Advisor Data

In [43]:
df[df['Advisor'].str.contains('Advisor 2')]

Name  \
MGP_ID                                    
28            \nHenry Francis Hrubecky    
62            \nRonald Raymond Hocking    
68               \nWilliam J. Hemmerle    
71                  \nWayne Allen Muth    
87                \nJames Elton Delany    
...                                 ...   
264147              \nDaniela  Mellado    
264148                   \nPablo  Vena    
264149                \nGonzalo  Chebi    
182845  \nDaria  Walukiewicz-Chrzaszcz    
182837               \nRaphael  Carroy    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
28                                                                                                                                                                           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1953</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
62                                                                                                                                                                           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1962</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
68                                                                                                                                                                           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1963</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
71                                                                                                                                                                           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1963</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
87                                                                                                                                                                           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="

41892 records with two advisors

In [44]:
df[df['Advisor'].str.contains('Advisor 3')]

Name  \
MGP_ID                            
388      \nJack Johnson Morava    
5292     \nCecil Calvert Craig    
10027         \nAmy Jean Kuntz    
11177   \nKuppusamy  Ravindran    
11640            \nPaul  Nevai    
...                         ...   
263814      \nCollin  Politsch    
263846        \nMelvern  Leung    
263874       \nWilliam R. Case    
263880        \nDamien  Dufour    
263997         \nQianqian  Zhu    

                                                                                                                                                                                                                                                                                                                                                                         Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                 
388                <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Rice University</span> 1968</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
5292        <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Michigan</span> 1927</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
10027    <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">The Ohio State University</span> 1974</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
11177      <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Kansas State University</span> 1996</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
11640               <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Hungarian Academy of Sciences</span> 1973</span>\n<img alt="Hungary" height="30" src="img/flags/Hungary.gif" style="border: 0; vertical-align: middle" title="Hungary" width="45"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                              ...   
263814  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Carnegie Mellon University</span> 2020</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
263846                    <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5

2688 records with three advisors

In [45]:
df[df['Advisor'].str.contains('Advisor 4')]

Name  \
MGP_ID                                     
20680                 \nTheodor  Peters    
20714                  \nFritz  Dueball    
42857    \nMaurice Henry Lecorney Pryce    
49678            \nHendrik Wolter Broer    
75157            \nHenk M. Schuttelaars    
...                                  ...   
261777  \nKashyapa Ganadithya Sirinanda    
262196           \nLekshmi  Dharmarajan    
262830               \nKjetil Olsen Lye    
263030                  \nLan Anh  Pham    
263880                 \nDamien  Dufour    

                                                                                                                                                                                                                                                                                                                                                                       Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                               
20680            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Humboldt-Universität zu Berlin</span> 1940</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
20714                    <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Dr. phil. <span style="color:\n  #006633; margin-left: 0.5em">Universität Berlin</span> 1937</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
42857       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Princeton University</span> 1937</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
49678   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Rijksuniversiteit Groningen</span> 1979</span>\n<img alt="Netherlands" height="30" src="img/flags/Netherlands.gif" style="border: 0; vertical-align: middle" title="Netherlands" width="45"/>\n</div>   
75157          <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Universiteit Utrecht</span> 1997</span>\n<img alt="Netherlands" height="30" src="img/flags/Netherlands.gif" style="border: 0; vertical-align: middle" title="Netherlands" width="45"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                            ...   
261777            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Melbourne</span> 2015</span>\n<img alt="Australia" height="30" src="img/flags/Australia.gif" style="border: 0; vertical-align: middle" title="Australia" width="60"/>\n</div>   
262196                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\

207 rows with four advisors

In [46]:
df[df['Advisor'].str.contains('Advisor 5')]

Name  \
MGP_ID                                
136256    \nKelvin Kian Loong Wong    
152317       \nGreg Martin Allenby    
159165   \nMohit Pankajroy Dalwadi    
164751         \nBradley S Stewart    
168155  \nPierre-Jacques  Courtois    
191272       \nFrancesco  Ballarin    
195251    \nIoannis M. Vandoulakis    
196343         \nKarim  Hedayatian    
215657        \nFrancisco  Azeredo    
219837         \nMatthias  Rungger    
222349           \nShannon  Harris    
224677       \nJean-Pierre  Chièze    
232527          \nMai   El-Shehaly    
239102        \nRongju Henry Zhang    
242063      \nMagda Gabriela  Sava    
254091       \nAlexios  Aivaliotis    
263880            \nDamien  Dufour    

                                                                                                                                                                                                                                                                                                                                                                                                  Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                          
136256                                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph. D. <span style="color:\n  #006633; margin-left: 0.5em">University of Adelaide</span> 2009</span>\n<img alt="Australia" height="30" src="img/flags/Australia.gif" style="border: 0; vertical-align: middle" title="Australia" width="60"/>\n</div>   
152317                            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">The University of Chicago</span> 1988</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
159165                            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">D.Phil. <span style="color:\n  #006633; margin-left: 0.5em">University of Oxford</span> 2014</span>\n<img alt="UnitedKingdom" height="30" src="img/flags/UnitedKingdom.gif" style="border: 0; vertical-align: middle" title="UnitedKingdom" width="60"/>\n</div>   
164751                               <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Virginia</span> 1988</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
168155           <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Docteur en Sciences Appliquées <span style="color:\n  #006633; margin-left: 0.5em">Université Catholique de Louvain</span> 1976</span>\n<img alt="Belgium" height="30" src="img/flags/Belgium.gif" style="border: 0; vertical-align: middle" title="Belgium" width="35"/>\n</div>   
191272                                                     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Politecnico di Milano</span> 2015</span>\n<img alt="Italy" height="30" src="img/flags/Italy.gif" style="border: 0; vertical-align: middle" title="Italy" width="45"/>\n</div>   
195251                                      <div style="line-height: 30px; text-a

In [47]:
df[df['Advisor'].str.contains('Advisor 5')].shape

(17, 12)

17 records with five advisors

In [48]:
df[df['Advisor'].str.contains('Advisor 6')]

Name  \
MGP_ID                           
224677  \nJean-Pierre  Chièze    
254091  \nAlexios  Aivaliotis    

                                                                                                                                                                                                                                                                                                                                                       Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                               
224677  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em">Université Paris-Sud XI - Orsay</span> 1983</span>\n<img alt="France" height="30" src="img/flags/France.gif" style="border: 0; vertical-align: middle" title="France" width="45"/>\n</div>   
254091          <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Université de Lyon</span> 2019</span>\n<img alt="France" height="30" src="img/flags/France.gif" style="border: 0; vertical-align: middle" title="France" width="45"/>\n</div>   

                                                                                                             Thesis  \
MGP_ID                                                                                                                
224677                                                              Structure et évolution du milieu interstellaire   
254091  Wave propagation and scattering at metamaterials' macroscopic boundaries via the relaxed micromorphic model   

                                                                      MSC  \
MGP_ID                                                                      
224677  Mathematics Subject Classification: 85—Astronomy and astrophysics   
254091                                                       No MSC given   

                                                                                                                                                                                                                                                                                                                                                                                                                                        Advisor  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                                                                            
224677  <p style="text-align: center; line-height: 2.75ex">Advisor 1: <a href="id.php?id=224676">Roland  Omnès</a><br/>Advisor 4: <a href="id.php?id=224678">Jean  Audouze</a><br/>Advisor 5: <a href="id.php?id=177164">James  Lequeux</a><br/>Advisor 5: <a href="id.php?id=224679">Robert  Dautray</a><br/>Advisor 6: <a href="id.php?id=223126">Joseph Ivor Silk</a><br/>Advisor 6: <a href="id.php?id=224680">Jean  Heyvaerts</a><br/></p>   
254091   <p style="text-align: center; line-height: 2.75ex">Advisor 1: <a href="id.php?id=254092">Manuel  Collet</a><br/>Advisor 2: <a href="id.php?id=254093">Ali  Daouadji</a><br/>Advisor 3: <a href="id.php?id=254094">Bruno  Lombard</a><br/>Advisor 4: <a href="id.php?id=254095">Angela  Madeo</a><br/>Advisor 5: <a href="id.php?id=139760">Patrizio  Neff</a><br/>Ad

2 records with six(!!) advisors

Extracting Advisor Names and IDs using lambda functions.

In [49]:
df['Advisor_1_Name'] = df.apply(lambda D: D['Advisor'].split('">')[1+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 1
                                else None, axis = 1)

df['Advisor_1_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[1].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 1
                                else None, axis = 1)

df['Advisor_2_Name'] = df.apply(lambda D: D['Advisor'].split('">')[2+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 2
                                else None, axis = 1)

df['Advisor_2_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[2].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 2
                                else None, axis = 1)

df['Advisor_3_Name'] = df.apply(lambda D: D['Advisor'].split('">')[3+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 3
                                else None, axis = 1)

df['Advisor_3_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[3].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 3
                                else None, axis = 1)

df['Advisor_4_Name'] = df.apply(lambda D: D['Advisor'].split('">')[4+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 4
                                else None, axis = 1)

df['Advisor_4_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[4].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 4
                                else None, axis = 1)

df['Advisor_5_Name'] = df.apply(lambda D: D['Advisor'].split('">')[5+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 5
                                else None, axis = 1)

df['Advisor_5_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[5].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 5
                                else None, axis = 1)

df['Advisor_6_Name'] = df.apply(lambda D: D['Advisor'].split('">')[6+1].split('</a')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 6
                                else None, axis = 1)

df['Advisor_6_MGP_ID'] = df.apply(lambda D: D['Advisor'].split('id=')[6].split('">')[0] 
                                if len(D['Advisor'].split('Advisor')) -1 >= 6
                                else None, axis = 1)

In [50]:
# convert empty advisor IDs to 0 to keep dtype int64

for i in range(1,7):
    df['Advisor_%s_MGP_ID'%(i)] = df['Advisor_%s_MGP_ID'%(i)].apply(str)\
    .apply(lambda C: '0' if not C.isdigit() else C)\
    .apply(int)

In [51]:
# number of advisors column
df['Num_advisors'] = df['Advisor'].str.split('Advisor').apply(len) -1

## Getting students and descendants counts

In [52]:
# number of students

df['num_students'] = df.apply(lambda D: 0 if D['Descendants'] == 'No students known.'
                              else D['Descendants'].split('has ')[-1].split(' student')[0], axis = 1)



In [53]:
df['num_students'] = df['num_students'].apply(str)

In [54]:
df[~df['num_students'].str.isdigit()]

Name  \
MGP_ID                        
182831  \nWilliam  Cousins    

                                                                                                                                                                                                                                                                                                                                                                              Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                      
182831  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">North Carolina State University</span> 2013</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   

                                                                         Thesis  \
MGP_ID                                                                            
182831  Boundary Conditions and Uncertainty Quantifications for\r\nHemodynamics   

                 MSC  \
MGP_ID                 
182831  No MSC given   

                                                                                                                           Advisor  \
MGP_ID                                                                                                                               
182831  <p style="text-align: center; line-height: 2.75ex">Advisor 1: <a href="id.php?id=45654">Pierre-Alain  Gremaud</a><br/></p>   

                                                                                      Descendants  \
MGP_ID                                                                                              
182831  Dissertation: \n\nBoundary Conditions and Uncertainty Quantifications for\r\nHemodynamics   

                                                                                                                                                                     MScNID  \
MGP_ID                                                                                                                                                                        
182831  <p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small">\n<a href="http://www.ams.org/mathscinet/MRAuthorID/988642">MathSciNet</a>\n</p>   

        Degree                           School       Country  Year  msc  \
MGP_ID                                                                     
182831  Ph.D.   North Carolina State University  UnitedStates  2013  NaN   

               Advisor_1_Name  Advisor_1_MGP_ID Advisor_2_Name  \
MGP_ID                                                           
182831  Pierre-Alain  Gremaud             45654           None   

        Advisor_2_MGP_ID Advisor_3_Name  Advisor_3_MGP_ID Advisor_4_Name  \
MGP_ID                                                                     
182831                 0           None                 0           None   

        Advisor_4_MGP_ID Advisor_5_Name  Advisor_5_MGP_ID Advisor_6_Name  \
MGP_ID                                                                     
182831                 0           None                 0           None   

        Advisor_6_MGP_ID  Num_advisors  \
MGP_ID                                   
182831                 0             1   

                                                                                     num_students  
MGP_ID                                                                                             
182831  Disserta

In [55]:
df.loc[182831,'num_students'] = '0'

In [56]:
df['num_students'] = df['num_students'].apply(int)

In [57]:
# number of descendants

df['num_descendants'] = df.apply(lambda D: 0 if D['Descendants'] == 'No students known.'
                              else D['Descendants'].split('and ')[-1].split(' desc')[0], axis = 1)

In [58]:
df['num_descendants'] = df['num_descendants'].apply(str)
df[~df['num_descendants'].str.isdigit()]

Name  \
MGP_ID                               
1       \nErnest Willard Anderson    
4         \nCharles Joseph Thorne    
7           \nCarl Eric Langenhop    
9             \nHenry David Block    
13        \nLawrence Edward Payne    
...                            ...   
182850            \nHubert  Comon    
64697           \nGeorge  Dassios    
182867     \nMichael  Rusinowitch    
64705             \nGyörgy  Turán    
64700      \nEugene Myron Barston    

                                                                                                                                                                                                                                                                                                                                                                                Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                        
1                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1933</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
4                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1941</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
7                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1948</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
9                   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1949</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
13                  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1950</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                     ...   
182850          <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Institut National Polytechnique de Grenoble</span> 1988</span>\n<img alt="France" height="30" src="img/flags/France.gif" style="border: 0; vertical-align: middle" title="France" width="45"/>\n</div>   
64697   <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span s

In [59]:
df.loc[1,'num_descendants']

'3 '

In [60]:
df['num_descendants'] = df['num_descendants'].str.strip(' ')

In [61]:
df[~df['num_descendants'].str.isdigit()]

Name  \
MGP_ID                        
182831  \nWilliam  Cousins    

                                                                                                                                                                                                                                                                                                                                                                              Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                      
182831  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">North Carolina State University</span> 2013</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   

                                                                         Thesis  \
MGP_ID                                                                            
182831  Boundary Conditions and Uncertainty Quantifications for\r\nHemodynamics   

                 MSC  \
MGP_ID                 
182831  No MSC given   

                                                                                                                           Advisor  \
MGP_ID                                                                                                                               
182831  <p style="text-align: center; line-height: 2.75ex">Advisor 1: <a href="id.php?id=45654">Pierre-Alain  Gremaud</a><br/></p>   

                                                                                      Descendants  \
MGP_ID                                                                                              
182831  Dissertation: \n\nBoundary Conditions and Uncertainty Quantifications for\r\nHemodynamics   

                                                                                                                                                                     MScNID  \
MGP_ID                                                                                                                                                                        
182831  <p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small">\n<a href="http://www.ams.org/mathscinet/MRAuthorID/988642">MathSciNet</a>\n</p>   

        Degree                           School       Country  Year  msc  \
MGP_ID                                                                     
182831  Ph.D.   North Carolina State University  UnitedStates  2013  NaN   

               Advisor_1_Name  Advisor_1_MGP_ID Advisor_2_Name  \
MGP_ID                                                           
182831  Pierre-Alain  Gremaud             45654           None   

        Advisor_2_MGP_ID Advisor_3_Name  Advisor_3_MGP_ID Advisor_4_Name  \
MGP_ID                                                                     
182831                 0           None                 0           None   

        Advisor_4_MGP_ID Advisor_5_Name  Advisor_5_MGP_ID Advisor_6_Name  \
MGP_ID                                                                     
182831                 0           None                 0           None   

        Advisor_6_MGP_ID  Num_advisors  num_students  \
MGP_ID                                                 
182831                 0             1             0   

                                        num_descendants  
MGP_ID                                                   
182831  Uncertainty Quantifications for\r\nHemodynamics

In [62]:
df.loc[182831,'num_descendants'] = '0'

In [63]:
df['num_descendants'] = df['num_descendants'].apply(int)

In [64]:
# recursive function to obtain set of ancestors for a record

def ancestors(rec):
    advisors = []
    for i in range(1,7):
        adv = df.loc[rec, 'Advisor_%s_MGP_ID'%(i)]
        if adv != 0:
            advisors.append(adv)
        else:
            continue
    
    if len(advisors) == 0:
        return set()
    else:
        adset = set(advisors)
        for adv in advisors:
            adset = adset.union(ancestors(adv))
        return adset
    
def anc_names(rec):
    anset = set()
    for anc in ancestors(rec):
        anset.add(df.loc[anc, 'Name'])
    print('Ancestors of ', df.loc[rec, 'Name'], 'are: ', anset, '\nNumber of ancestors is ', len(anset))
    return anset
    
    

In [65]:
def students(rec):
    stset = []
    for j in range(1,7):
        for stu in df[df['Advisor_%s_MGP_ID'%(j)] == rec].index:
            stset.append(stu)
    return set(stset)

In [66]:
def st_names(rec):
    names = set()
    for id in students(rec):
        names.add(df.loc[id,'Name'])
    print(df.loc[rec,'Name'], ' has ', len(names), ' students with names: ', names)
    return names

In [67]:
#depth first search for descendants

def desc_DFS(rec, series):
    series[rec] = True
    for v in students(rec):
        if series[v] == False:
            desc_DFS(v, series)
    return df[series]['Name']
    

In [68]:
def descendants(rec):
    D = desc_DFS(rec, pd.Series(False, index = df.index))
    return D[D.index != rec]

## Cleaning up name column

In [69]:
# remove \n from name column

df['Name'] = df['Name'].str.strip('\n')

In [70]:
df[df['Name'].str[-1] != ' ']

Name  \
MGP_ID        
193664        

                                                                                                                                                                                    Degree_Info  \
MGP_ID                                                                                                                                                                                            
193664  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\n</div>   

       Thesis           MSC Advisor         Descendants  \
MGP_ID                                                    
193664         No MSC given    None  No students known.   

                                                                                           MScNID  \
MGP_ID                                                                                              
193664  <p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small">\n</p>   

       Degree School  Country  Year  msc Advisor_1_Name  Advisor_1_MGP_ID  \
MGP_ID                                                                      
193664                Unknown     0  NaN           None                 0   

       Advisor_2_Name  Advisor_2_MGP_ID Advisor_3_Name  Advisor_3_MGP_ID  \
MGP_ID                                                                     
193664           None                 0           None                 0   

       Advisor_4_Name  Advisor_4_MGP_ID Advisor_5_Name  Advisor_5_MGP_ID  \
MGP_ID                                                                     
193664           None                 0           None                 0   

       Advisor_6_Name  Advisor_6_MGP_ID  Num_advisors  num_students  \
MGP_ID                                                                
193664           None                 0             0             0   

        num_descendants  
MGP_ID                   
193664                0

All names have a space at the end.

In [71]:
# removing space at end

df['Name'] = df['Name'].str[:-1]

Some names have double spaces.

In [72]:
df['Name'] = df['Name'].str.replace('  ', ' ')

## Extracting MathSciNet ID

In [73]:
df['MScNetID'] = df['MScNID'].apply(lambda x: None if 'href' not in x
                                                     else (x.split('ID/')[-1].split('">')[0]))

In [74]:
def none_bool(x):
    if x == None:
        return True
    else: 
        return False

In [75]:
df[df['MScNetID'].apply(none_bool)]

Name  \
MGP_ID                               
1          Ernest Willard Anderson   
2                    Archie Higdon   
10                 Frank E. Bortle   
11           Alfred E. Engelbrecht   
17             Arnold Marion Wedel   
...                            ...   
264148                  Pablo Vena   
264149               Gonzalo Chebi   
264150               Rafael Vilela   
264152  Pedro Yóssis Silva Barbosa   
264153                Shaoting Lin   

                                                                                                                                                                                                                                                                                                                                                                                    Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                            
1                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1933</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
2                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1936</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
10                      <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1949</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
11                      <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1949</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
17                      <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1951</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                         ...   
264148                     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Universidad de Buenos Aires</span> 2019</span>\n<img alt="Argentina" height="30" src="img/flags/Argentina.gif" style="border: 0; vertical-align: middle" title="Argentina" width="60"/>\n</div>   
264149                     <div style="line-height: 

110396 rows with `'MScNetID'` value `None` because no `'href'` in the MScN string

In [76]:
df[(~df['MScNetID'].apply(none_bool)) & (df['MScNetID'].str.contains('p'))]

Name  \
MGP_ID                                        
234                          Wolfgang Krull   
399                          Curtis P. Bell   
519                    Osip Ivanovich Somov   
4332                         William Prager   
4926    H. C. Marston (Harold Calvin) Morse   
...                                     ...   
199357                        Nicole Oresme   
207338               Johann Georg Rosenhain   
234824                         James Hutton   
235010              Pierre Louis Maupertuis   
235011               Alexis Claude Clairaut   

                                                                                                                                                                                                                                                                                                                                                                               Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                       
234     <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Albert-Ludwigs-Universität Freiburg im Breisgau</span> 1922</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
399                <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">University of Georgia</span> 1963</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
519                            <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">St. Petersburg State University</span> </span>\n<img alt="Russia" height="30" src="img/flags/Russia.gif" style="border: 0; vertical-align: middle" title="Russia" width="45"/>\n</div>   
4332                <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Dr.-Ing. <span style="color:\n  #006633; margin-left: 0.5em">Technische Universität Darmstadt</span> 1926</span>\n<img alt="Germany" height="30" src="img/flags/Germany.gif" style="border: 0; vertical-align: middle" title="Germany" width="50"/>\n</div>   
4926                  <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Harvard University</span> 1917</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                    ...   
199357                                                                                                                                                                                             <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em"> <span style="color:\n  #006633; margin-left: 0.5em"></span> </span>\

In [77]:
df['MScNetID'] = df['MScNetID'].apply(lambda C: None if C == '<p style="text-align: center; margin-top: 0; margin-bottom: 0px; font-size: small'
                                      else C)


In [78]:
df[~df['MScNetID'].apply(none_bool)]

Name  \
MGP_ID                          
3            Donald Hill Rock   
4       Charles Joseph Thorne   
5           Ralph Harry Tripp   
6           William B. Stiles   
7         Carl Eric Langenhop   
...                       ...   
64700    Eugene Myron Barston   
64693           Kai-Jaung Pei   
64714       Marek W. Kaminski   
182835          Daniel Seidel   
182843           Robert Benim   

                                                                                                                                                                                                                                                                                                                                                                                      Degree_Info  \
MGP_ID                                                                                                                                                                                                                                                                                                                                                                                              
3                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1939</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
4                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1941</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
5                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1942</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
6                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1945</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
7                         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Iowa State University</span> 1948</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
...                                                                                                                                                                                                                                                                                                                                                                                           ...   
64700                       <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span style="margin-right: 0.5em">Ph.D. <span style="color:\n  #006633; margin-left: 0.5em">Stanford University</span> 1964</span>\n<img alt="UnitedStates" height="30" src="img/flags/UnitedStates.gif" style="border: 0; vertical-align: middle" title="UnitedStates" width="57"/>\n</div>   
64693         <div style="line-height: 30px; text-align: center; margin-bottom: 1ex">\n<span s

## Finding duplicate MathSciNet IDs

Check for duplicated MScNetID entries

In [79]:
mscncount = df.groupby('MScNetID').count()

dup = mscncount[mscncount['Name']>1].sort_values('Name',ascending=False)

# getting MGP_IDs
dups = list(dup.index)

df['dup_bool'] = df['MScNetID'].apply(lambda C: True if C in dups else False)

multi = df[df['dup_bool']]

multi.shape

(238, 29)

238 duplicated MScNetID entries

In [80]:
# dict of MGP_IDs:MScN_IDs that were missed due to MGP error

redo_dict = {467:483015, 
             239638:939540, 
             239639:None, 
             239640:None, 
             240390:None, 
             242852:981207, 
             240642:None,
             240643:1116130, 
             240644:None, 
             240645:None,
             242854:1340983,
             240461:1379454,
             240466:1119891,
             240476:1372483,
             193987:None,
             220405:1377934,
             220406:1299512,
             240460:None,
             240464:None,
             240470:None,
             91549:636696,
             240396:1341326,
             240398:None,
             240399:1172854,
             240400:None,
             240401:None,
             233558:None,
             233559:1326846,
             240468:None,
             240473:None,
             240462:1234379,
             240463:None,
             240392:875239,
             240393:None,
             240394:974778,
             240471:None,
             240646:1379690,
             233524:None,
             220374:None,
             239834:633323,
             45905:1254428,
             261630:None,
             240641:998355,
             239716:1380212,
             250350:None,
             203863:None,
             190248:None,
             233835:None,
             249532:1163257,
             239825:782394,
             69659:None,
             240475:None,
             106305:None,
             263857:1341609,
             234471:None,
             226090:None,
             239397:1135107,
             243561:None,
             239966:947586,
             256199:1133915,
             243588:879054,
             245235:1050614,
             236262:None,
             43447:1248472,
             6277:None,
             195084:None,
             260352:1079752,
             78303:None,
             217258:1373996,
             201634:235506,
             240027:None,
             254991:None,
             255306:882749,
             236999:None,
             216074:230367,
             60744:None,
             197423:None,
             32464:None,
             239480:None,
             244152:None,
             113745:None,
             244500:201995,
             221233:None,
             231153:None,
             248452:None,
             156801:1060570,
             201922:984063,
             233047:None,
             206025:None,
             255560:None,
             209514:None,
             207319:None,
             204339:None,
             140308:1329630,
             231230:None,
             174075:None,
             194321:None,
             229598:None,
             237224:None,
             179871:1080275,
             167227:None,
             217134:None,
             8362:None,
             227165:None,
             236542:None,
             72208:None,
             174660:None,
             230727:None,
             207645:None,
             259068:None,
             149943:None,
             255074:None,
             127674:None,
             177680:None,
             239383:None,
             204922:None,
             250218:None,
             198543:None,
             248345:None,
             240192:None,
             253506:None,
             153024:None,
             258153:None,
             227807:None,
             262337:None,
             126065:None,
             137109:None,
             194219:None,
             261293:None,
             98025:1371696,
             209193:None,
             93854:None,
             234647:916233,
             255689:None,
             106184:None,
             242196:None,
             143647:None,
             234647:None,
             5638:190631
            }

for mgpid in redo_dict.keys():
    df.loc[mgpid,'MScNetID'] = redo_dict[mgpid]
    
df['MScNetID'] = df['MScNetID'].apply(lambda C: str(C) if C!=None else C)

In [81]:
# these are the records of people with duplicate entries
# these add the information from the droped duplicate row

df.loc[242445, ['Advisor_2_Name','Advisor_2_MGP_ID']] = ['Abedelaziz Mohaisen', 167150]

df.loc[218128, ['Advisor_2_Name', 'Advisor_2_MGP_ID']] = ['Patricio Luis Felmer', 11390]

df.loc[220918,'MSC'] = 55

df.loc[233082,['num_students','num_descendants']] = [1,9]

df.loc[9633, ['Advisor_2_Name','Advisor_2_MGP_ID']] = ['Joshua Chover', 5135]

df.loc[257640,['Advisor_2_Name','Advisor_2_MGP_ID']] = ['Casimir Alexander Kulikowski', 70194]

df.loc[120115,['Advisor_4_Name','Advisor_4_MGP_ID']] = ['Remco Theodoor Peters', 120115]

df.loc[244136,['Advisor_2_Name','Advisor_2_MGP_ID']] = ['Rainer Nagel', 21589]

df.loc[256396, 'Thesis'] = 'Existence of solutions for some nonlinear elliptic problems'

df.loc[252369, ['Advisor_3_Name','Advisor_3_MGP_ID']] = ['Nikolaos D. Katopodes', 252388]

In [82]:
# These records have advisors with duplicate entries 
# and the original reference to the advisor uses the 
# entry that is being dropped.

df.loc[206047, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Nati Linial', 63895]

df.loc[238660, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Volodimir Leonidovich Makarov', 187063]

df.loc[65262, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Norbert Peters', 233082]

df.loc[223968, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Jerzy Franciszek Plebański', 119928]

df.loc[197270, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Jorge Manuel Sotomayor Tello', 69192]

df.loc[199124, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['David José Fernández Cabrera', 223970]

df.loc[238114, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Xiang-Gen Xia', 173753]

df.loc[242961, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Gui-Qiang G. Chen', 38667]

df.loc[178268, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Hongze Li (李红泽)', 204934]

df.loc[207215, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Marco Maria Luigi Sammartino', 188663]

df.loc[232091, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Hector Fidencio Sanchez-Morgado', 6852]

df.loc[231388, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Adriano Tomassini', 171044]

df.loc[45308, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['David John Stevenson', 227187]

df.loc[215102, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['K. Suresh Kumar', 123774]

df.loc[212856, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Frederic Paik Schoenberg', 34439]

df.loc[243237, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Vitor Domingos Martins de Araújo', 54150]

df.loc[243238, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Vitor Domingos Martins de Araújo', 54150]

df.loc[257136, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Zhi Ding', 220353]

df.loc[257137, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Zhi Ding', 220353]

df.loc[237126, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Jayanthan A V', 37588]

df.loc[241593, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Mrinal Kanti Das', 9777]

df.loc[206697, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Abbas Syed', 141151]

df.loc[239385, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Dimas Jose Goncalves', 146882]

df.loc[250923, ['Advisor_1_Name', 'Advisor_1_MGP_ID']] = ['Sourav Pal', 251547]

df.loc[239940, ['Advisor_2_Name', 'Advisor_2_MGP_ID']] = ['José Ángel Peláez', 77913]

df.loc[258001, ['Advisor_2_Name', 'Advisor_2_MGP_ID']] = ['Ragnar Freij-Hollanti', 165053]



Check for any other `MScNetID` duplicates

In [83]:
mscncount = df.groupby('MScNetID').count()

dup = mscncount[mscncount['Name']>1].sort_values('Name',ascending=False)

# getting MGP_IDs
dups = list(dup.index)

df['dup_bool'] = df['MScNetID'].apply(lambda C: True if C in dups else False)

multi = df[df['dup_bool']]

multi.shape

(0, 29)

In [84]:
df[~df['MScNetID'].apply(none_bool)].shape

(148554, 29)

In [85]:
# redo_list = [i for i in redo_dict.values() if i!= None]
# len(redo_list)

In [86]:
# pd.Series(redo_list).to_csv('MScN/MScN_redo_list.csv')

In [87]:
df.groupby('MScNetID').count().shape

(148554, 28)

## Dropping and rearranging columns

In [88]:
df.drop(['MSC','Advisor','Descendants','MScNID','Degree_Info','dup_bool'], axis = 1, inplace = True)

# change some column names
df.columns = ['Name', 'Thesis', 'Degree', 'School', 'Country', 'Year', 'MSC', 'Advisor_1_Name',
       'Advisor_1_MGP_ID', 'Advisor_2_Name', 'Advisor_2_MGP_ID',
       'Advisor_3_Name', 'Advisor_3_MGP_ID', 'Advisor_4_Name',
       'Advisor_4_MGP_ID', 'Advisor_5_Name', 'Advisor_5_MGP_ID',
       'Advisor_6_Name', 'Advisor_6_MGP_ID', 'num_advisors', 'num_students',
       'num_descendants', 'MScNetID']

# change order of columns

df = df[['Name', 'MScNetID', 'Degree', 'School', 'Country', 'Year', 'Thesis', 'MSC', 'num_students',
       'num_descendants', 'num_advisors', 'Advisor_1_Name',
       'Advisor_1_MGP_ID', 'Advisor_2_Name', 'Advisor_2_MGP_ID',
       'Advisor_3_Name', 'Advisor_3_MGP_ID', 'Advisor_4_Name',
       'Advisor_4_MGP_ID', 'Advisor_5_Name', 'Advisor_5_MGP_ID',
       'Advisor_6_Name', 'Advisor_6_MGP_ID']]

cols = ['Name', 'MScNetID', 'Degree', 'School', 'Country', 'Year', 'Thesis', 'MSC', 'num_students',
       'num_descendants', 'num_advisors', 'Advisor_1_Name',
       'Advisor_1_MGP_ID', 'Advisor_2_Name', 'Advisor_2_MGP_ID',
       'Advisor_3_Name', 'Advisor_3_MGP_ID', 'Advisor_4_Name',
       'Advisor_4_MGP_ID', 'Advisor_5_Name', 'Advisor_5_MGP_ID',
       'Advisor_6_Name', 'Advisor_6_MGP_ID']

In [89]:
df.shape

(259422, 23)

## Cleaning MathSciNet Table

In [90]:
#  ms_list = [pd.read_csv('MScN/MScN_Author%s,%s.csv'%(K*1000, (K+1)*1000)) for K in range(0,150)]+[pd.read_csv('MScN/MScN_Author0,44.csv')]+[pd.read_csv('MScN/MScN_Author0,387.csv')]

#  ms = pd.concat(ms_list,ignore_index=True)

# ms.to_csv('MScN/MScN_Author_scrape.csv')

In [91]:
ms = pd.read_csv('MScN/MScN_Author_scrape.csv')

In [92]:
ms.shape

(148796, 6)

In [93]:
ms['MScN_ID'] = ms['MScN_ID'].apply(str)

In [94]:
# drop non-digit MScN_ID entries


ms = ms[ms['MScN_ID'].str.isdigit()]

In [95]:
# drop duplicates in ms table
ms.drop_duplicates(subset = 'MScN_ID', inplace=True)

In [96]:
ms.shape

(148191, 6)

In [97]:
mscount = ms.groupby('MScN_ID').count().sort_values('Name',ascending=False)

msdup = mscount[mscount['Name']>1]

# getting MGP_IDs
msdups = list(msdup.index)

ms['msdup_bool'] = ms['MScN_ID'].apply(lambda C: True if C in msdups else False)

msmulti = ms[ms['msdup_bool']]

msmulti.shape

(0, 7)

In [98]:
# drop MScN_ID because it doesn't correspond to the proper person

ms = ms[~(ms['MScN_ID'] == '713534')]

In [99]:
ms_mscns = set(ms['MScN_ID'])
df_mscns = set(df[~df['MScNetID'].apply(none_bool)]['MScNetID'])

print(len(ms_mscns))
print(len(df_mscns))
print(len(df_mscns) - len(ms_mscns))

148190
148554
364


In [100]:
in_ms = ms_mscns.difference(df_mscns)
print(len(in_ms))
print(in_ms)

0
set()


In [101]:
# pd.Series(list(in_ms)).to_csv('missed_mscns2.csv')

In [102]:
in_df = df_mscns.difference(ms_mscns)
len(in_df)

364

The rest of the mscn_ids in `df` that are not in `ms` do not correspond to an actual MathSciNet page.  Some of these can maybe be fixed, the set is small enough to leave.

In [103]:
for x in list(in_df):
    df['MScNetID'] = df['MScNetID'].apply(lambda C: None if C == x else C)


Checking that the MathSciNet IDs align

In [104]:
ms_mscns = set(ms['MScN_ID'])
df_mscns = set(df[~df['MScNetID'].apply(none_bool)]['MScNetID'])

print(len(ms_mscns))
print(len(df_mscns))
print(len(df_mscns) - len(ms_mscns))

148190
148190
0


In [105]:
in_ms = ms_mscns.difference(df_mscns)
print(len(in_ms))


0


In [106]:
in_df = df_mscns.difference(ms_mscns)
len(in_df)

0

In [107]:
intersect = df_mscns.intersection(ms_mscns)
len(intersect)

148190

## Extracting info from scraped MathSciNet data

In [108]:
ms.head()

Unnamed: 0  Unnamed: 0.1 MScN_ID  \
0           0             0  527409   
1           1             1  552938   
2           2             2  555156   
3           3             3  545267   
4           4             4  110050   

                                        Name  \
0     MR: \n    Rock, Donald Hill - 527409\n   
1         MR: \n    Thorne, C. J. - 552938\n   
2          MR: \n    Tripp, R. H. - 555156\n   
3         MR: \n    Stiles, W. B. - 545267\n   
4  MR: \n    Langenhop, Carl Eric - 110050\n   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Data  \
0                                           [<td ng-show="profile.nameInNativeScript">Full name in native script: </td>, <td ng-show="profile.nameInNativeScript">{{profile.nameInNativeScript}}</td>, <td>Email:</td>, <td><a href="mailto:{{profile.email}}" target="_top">{{profile.email}}</a></td>, <td ng-show="profile.website">Website:</td>, <td><a href="{{profile.website}}" target="blank">{{profile.website}}</a></td>, <td>MR Author ID:</td>, <td>527409</td>, <td>Earliest Indexed Publication:</td>, <td>\n<strong>1939</strong>\n</td>, <td>Total Publications:</td>, <td>2</td>]   
1   [<td ng-show="profile.nameInNativeScript">Full name in native script: </td>, <td ng-show="profile.nameInNativeScript">{{profile.nameInNativeScript}}</td>, <td>Email:</td>, <td><a href="mailto:{{profile.email}}" target="_top">{{profile.email}}</a></td>, <td ng-show="profile.website">Website:</td>, <td><a href="{{profile.website}}" target="blank">{{profile.website}}</a></td>, <td>MR Author ID:</td>, <td>552938</td>, <td>Earliest Indexed Publication:</td>, <td>\n<strong>1940</strong>\n</td>, <td>Total Publications:</td>, <td>14</td>, <td>Total Citations:</td>, <td>6</td>]   
2                                           [<td ng-show="profile.nameInNativeScript">Full name in native script: </td>, <td ng-show="profile.nameInNativeScript">{{profile.nameInNativeScript}}</td>, <td>Email:</td>, <td><a href="mailto:{{profile.email}}" target="_top">{{profile.email}}</a></td>, <td ng-show="profile.website">Website:</td>, <td><a href="{{profile.website}}" target="blank">{{profile.website}}</a></td>, <td>MR Author ID:</td>, <td>555156</td>, <td>Earliest Indexed Publication:</td>, <td>\n<strong>1940</strong>\n</td>, <td>Total Publications:</td>, <td>1</td>]   
3                                           [<td ng-show="profile.nameInNativeScript">Full name in native script: </td>, <td ng-show="profile.nameInNativeScript">{{profile.nameInNativeScript}}</td>, <td>Email:</td>, <td><a href="mailto:{{profile.email}}" target="_top">{{profile.email}}</a></td>, <td ng-show="profile.website">Website:</td>, <td><a href="{{profile.website}}" target="blank">{{profile.website}}</a></td>, <td>MR Author ID:</td>, <td>545267</td>, <td>Earliest Indexed Publication:</td>, <td>\n<strong>1947</strong>\n</td>, <td>Total Publications:</td>, <td>1</td>]   
4  [<td ng-show="profile.nameInNativeScript">Full name in native script: </td>, <td ng-show="profile.nameInNativeScript">{{profile.nameInNativeScript}}</td>, <td>Email:</td>, <td><a href="mailto:{{profile.email}}" target="_top">{{profile.email}}</a></td>, <td ng-show="profile.website">Website:</td>, <td><a href="{{profile.website}}" target="blank">{{profile.website}}</a></td>, <td>MR Author ID:</td>, <td>110050</td>, <td>Earliest Indexed Publication:</td>, <td>\n<strong>1948</strong>\n</td>, <td>Total Publications:</td>, <td>31</td>, <td>Total Citations:</td

In [109]:
ms.shape

(148190, 7)

In [110]:
ms.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'MScN_ID', 'Name', 'Data', 'Collab_Subj',
       'msdup_bool'],
      dtype='object')

In [111]:
ms.set_index('MScN_ID', inplace=True)

ms.drop(['Unnamed: 0', 'Unnamed: 0.1', 'msdup_bool'], axis=1, inplace=True)

# getting Name
ms['Name1'] = ms['Name'].apply(lambda C: C.split('\n    ')[-1].split(' - ')[0])


# getting earliest indexed publication
ms['Earliest_Pub'] = ms['Data'].apply(lambda C: C.split('<strong>')[-1].split('</strong')[0])

# converting missing earliest pub data to 0
ms['Earliest_Pub'] = ms['Earliest_Pub'].apply(lambda C: C if C.isdigit() else '0')

# convert earliest pub to type int
ms['Earliest_Pub'] = ms['Earliest_Pub'].apply(int)


# getting total pubs
ms['Total_Pubs'] = ms['Data'].apply(lambda C: C.split('Total Publications:</td>, <td>')[-1].split('<')[0])

# replace missing total pub values with 0
ms['Total_Pubs'] = ms['Total_Pubs'].apply(lambda C: '0' if C == '[' else C)

# convert total pub column to type int
ms['Total_Pubs'] = ms['Total_Pubs'].apply(int)


# getting total related publications
ms['Total_Rel_Pubs'] = ms['Data'].apply(lambda C: C.split('Total Related Publications:</td>, <td>')[-1].split('<')[0] 
                                        if 'Related' in C
                                        else '0')

# convert total rel pubs column to type int
ms['Total_Rel_Pubs'] = ms['Total_Rel_Pubs'].apply(int)


# getting total Citations
ms['Total_Citations'] = ms['Data'].apply(lambda C: C.split('Total Citations:</td>, <td>')[-1].split('<')[0])

# replace missing citation values with 0
ms['Total_Citations'] = ms['Total_Citations'].apply(lambda C: '0' if C == '[' else C)

# convert citation column to type int
ms['Total_Citations'] = ms['Total_Citations'].apply(int)

def num_collabs(s):
    return len(s.split('MR Author ID ')) - 1

def col_list(s):
    
    return [[s.split('MR Author ID ')[i+1].split('">')[0], 
             s.split('MR Author ID ')[i+1].split('">')[1].split('</a>')[0]]
           for i in range(num_collabs(s))]



def col_ids(ls):
    return [x[0] for x in ls]
def col_names(ls):
    return [x[1] for x in ls]

# getting tuple of collaborator ids and names
ms['Collaborator_Data'] = ms['Collab_Subj'].apply(col_list)

# getting list of collaborator ids
ms['Collaborator_IDs'] = ms['Collaborator_Data'].apply(col_ids)

# getting list of collaborator names
ms['Collaborator_Names'] = ms['Collaborator_Data'].apply(col_names)

def num_subjects(s):
    return len(s.split('Primary Class ')) - 1

def subject_list(s):
    
    return [s.split('Primary Class ')[i+1].split('">')[0]
           for i in range(num_subjects(s))]

# getting list of subjects (in MSC)
ms['Subjects'] = ms['Collab_Subj'].apply(subject_list)

ms.drop(['Name', 'Data', 'Collab_Subj'], axis = 1, inplace = True)

ms.columns = ['Name_MScN', 'Earliest_Pub', 'Total_Pubs', 'Total_Rel_Pubs', 'Total_Citations', 'CollabData', 'CollabIDs', 'CollabNames', 'Subjects']

ms.drop('CollabData', axis=1, inplace=True)

ms['Num_Collaborators'] = ms['CollabIDs'].apply(len)

ms['Num_Subjects'] = ms['Subjects'].apply(len)

ms['Total_Citations'] = ms['Total_Citations'].apply(lambda C: '0' if C == '[' else C)



ms['CollabIDs'] = ms['CollabIDs'].apply(lambda C: None if C == [] else C)
ms['CollabNames'] = ms['CollabNames'].apply(lambda C: None if C == [] else C)

ms['Subjects'] = ms['Subjects'].apply(lambda C: None if C == [] else C)

ms.head()

Name_MScN  Earliest_Pub  Total_Pubs  Total_Rel_Pubs  \
MScN_ID                                                                   
527409      Rock, Donald Hill          1939           2               0   
552938          Thorne, C. J.          1940          14               0   
555156           Tripp, R. H.          1940           1               0   
545267          Stiles, W. B.          1947           1               0   
110050   Langenhop, Carl Eric          1948          31               0   

         Total_Citations  \
MScN_ID                    
527409                 0   
552938                 6   
555156                 0   
545267                 0   
110050                68   

                                                                                      CollabIDs  \
MScN_ID                                                                                           
527409                                                                                 [364764]   
552938                                                  [27980, 426339, 433988, 444100, 331201]   
555156                                                                                 [462675]   
545267                                                                                     None   
110050   [194993, 441768, 462527, 88005, 92705, 300870, 113355, 121270, 526800, 158245, 218955]   

                                                                                                                                                                                                  CollabNames  \
MScN_ID                                                                                                                                                                                                         
527409                                                                                                                                                                                 [Weinstein, Alexander]   
552938                                                                                                             [Atanasoff, John Vincent, Claassen, R. W., Deverall, L. I., Fletcher, H. J., Morel, J. P.]   
555156                                                                                                                                                                                         [Holl, Dio L.]   
545267                                                                                                                                                                                                   None   
110050   [Banks, Harvey Thomas, Farnell, A. B., Hogan, D. A., Hooker, John W., Jacobs, Marc Q., Kirk, R. B., Levinson, Norman, Mathews, Jerold C., Rivera Rodas, Hernán, Seifert, George, Wright, William E.]   

                                             Subjects  Num_Collaborators  \
MScN_ID                                                                    
527409                                       [36, 73]                  1   
552938                           [41, 70, 73, 65, 33]                  5   
555156                                           [73]                  1   
545267                                           [73]                  0   
110050   [49, 05, 68, 36, 46, 69, 45, 15, 34, 60, 93]                 11   

         Num_Subjects  
MScN_ID                
527409              2  
552938              5  
555156              1  
545267              1  
110050             11

In [112]:
df.to_csv('MGP/MGP_clean.csv')
ms.to_csv('MScN/MScN_Author_clean.csv')

## Joining MGP and MScN

In [113]:
am = df.join(ms, how='left', on = 'MScNetID', rsuffix = 'MScN')

In [114]:
am.shape

(259422, 33)

In [115]:
am.head()

Name MScNetID  Degree                 School  \
MGP_ID                                                                    
1       Ernest Willard Anderson     None  Ph.D.   Iowa State University   
2                 Archie Higdon     None  Ph.D.   Iowa State University   
3              Donald Hill Rock   527409  Ph.D.   Iowa State University   
4         Charles Joseph Thorne   552938  Ph.D.   Iowa State University   
5             Ralph Harry Tripp   555156  Ph.D.   Iowa State University   

             Country  Year  \
MGP_ID                       
1       UnitedStates  1933   
2       UnitedStates  1936   
3       UnitedStates  1939   
4       UnitedStates  1941   
5       UnitedStates  1942   

                                                                                     Thesis  \
MGP_ID                                                                                        
1             Statics of Special Types of Homogeneous Elastic Slabs with Variable Thickness   
2                                           Stresses in Moderately Thick Rectangular Plates   
3                                                  Finite Strain Analysis in Elastic Theory   
4       The Approximate Solution of Linear Differential Equations by the Use of Functionals   
5                                     Statical Equilibrium of Skew and Sector-Shaped Plates   

        MSC  num_students  num_descendants  num_advisors  \
MGP_ID                                                     
1        74             3                3             1   
2        74             0                0             1   
3       NaN             0                0             1   
4       NaN             2                2             1   
5       NaN             0                0             1   

                Advisor_1_Name  Advisor_1_MGP_ID Advisor_2_Name  \
MGP_ID                                                            
1               Dio Lewis Holl               258           None   
2               Dio Lewis Holl               258           None   
3               Dio Lewis Holl               258           None   
4       John Vincent Atanasoff               239           None   
5               Dio Lewis Holl               258           None   

        Advisor_2_MGP_ID Advisor_3_Name  Advisor_3_MGP_ID Advisor_4_Name  \
MGP_ID                                                                     
1                      0           None                 0           None   
2                      0           None                 0           None   
3                      0           None                 0           None   
4                      0           None                 0           None   
5                      0           None                 0           None   

        Advisor_4_MGP_ID Advisor_5_Name  Advisor_5_MGP_ID Advisor_6_Name  \
MGP_ID                                                                     
1                      0           None                 0           None   
2                      0           None                 0           None   
3                      0           None                 0           None   
4                      0           None                 0           None   
5                      0           None                 0           None   

        Advisor_6_MGP_ID          Name_MScN  Earliest_Pub  Total_Pubs  \
MGP_ID                                                                  
1                      0                NaN           NaN         NaN   
2                      0                NaN           NaN         NaN   
3                      0  Rock, Donald Hill        1939.0         2.0   
4                      0      Thorne, C. J.        1940.0        14.0   
5                      0       Tripp, R. H.        1940.0         1.0   

        Total_Rel_Pubs  Total_Citations  \
MGP_ID                                    
1                  NaN              NaN   
2                  NaN    

In [116]:
# return earliest pub, total pubs, total rel pubs, total citations, num collaborators, and num_subjects 
# to type int with -1 serving for empty info

cols = ['Earliest_Pub', 'Total_Pubs', 'Total_Rel_Pubs', 'Total_Citations', 'Num_Collaborators', 'Num_Subjects']

for col in cols:
    am[col] = am[col].apply(str)\
    .apply(lambda C: '0' if C == '0.0' else C.strip('.0'))\
    .apply(lambda C: -1 if C=='nan' else int(C))

In [117]:
am[(am['Total_Pubs']!= -1)].shape

(148190, 33)

In [118]:
am[(am['num_students'] > 0) & (am['Total_Pubs']!= -1)].shape

(41037, 33)

41,037 records with nonempty publication data and with at least one student.  This is an excellent size to use for training/testing.

In [119]:
am.to_csv('MGP_MScN.csv')
am.to_excel('MGP_MScN.xlsx')

## Summary

### MGP data frame

1. Importing the raw data from `MGP_scrape.csv` into the dataframe `df`, we see we initially have 259533 rows.
2. We then drop two columns from coming from the import, and we drop a list of rows that we have determined earlier to either be duplicates or contain no data.  We also drop the duplicates.  This leaves us with 259423 rows.
3. The `Thesis` column is not likely to form a feature, the only cleaning for this column is to strip the '\n's.
4. Next we extracted the degree title, school, and country data from the `Degree_Info` columns using string methods.  Missing country values were replaced with 'Unknown'.
5. Then we extracted the year information.  This required some attention because some errors occurred when the year information was entered for certain records.
6. Next we extracted the MSC (Math Subject Classification) number for each record.  Missing values were replaced with `np.nan`.
7. Next we made columns for the advisor data.  The max number of advisors a record has is 6, so there are 6 pairs of advisor columns.  Each pair is made up of the advisor's name and the advisor's `MGP_ID`.  Missing values were replaced with 0 so the columns can by of type int.
8. Next we cleaned up the `Name` column.  Every name had a space at the end, and names without a middle name had a double space between first and last name
9. We then extracted the number of students and number of descendants for each record.  We also wrote some functions to compile the list of ancestors, students, and descendants of a given function.  The descendants function is a depth-first search.
10. We next extracted the MathSciNet IDs for each record. We then checked for duplicate MathSciNet IDs.  There were many that we sorted out in cells following the MathSciNet ID extraction.  For instance there were many MScNetIDs that were assigned to multipl MGP_IDs.  So we found the MGP_IDs which actually belonged with the MScNetIDs and appropriately replaced the mislabelled IDs.
11. We then dropped and rearranged several columns--mainly ones containing the raw scraped data and one created for a boolean series.



### MScN data frame

1. Importing the raw data from `MScN_Author_scrape.csv` into the dataframe `ms`, we see we initially have 148796 rows. 
2. We then dropped all duplicate rows (keeping the first of each duplicate) and dropped all entries with non-digit MScN_IDs.  We also dropped one record because it is attached to the incorrect MGP_ID.  This left us with 148190 rows
3. We next checked to see if the collection of MScNetIDs in `df` matched with those in `ms`.  Apparently the ones in `ms` are all contained in `df`, but `df` had 364 more IDs than `ms`.  It was found that these IDs are faulty and do not correspond to an actual MathSciNet Author page--possibly due to some clerical error.  Some of these could be fixed by adjusting a digit, but it was decided to just convert these 364 IDs to `None` in `df`.  At the end of this process, both dataframes have the same exact collection of functioning MathSciNet author IDs.
4. We next moved to extract the data from the raw scrape of the MathSciNet pages.
5. We extracted the `Earliest_Pub`, `Total_Pubs`, `Total_Rel_Pubs`, `Total_Citations`, `CollabIDs`, `CollabNames`, `Subjects`, `Num_Collaborators`, `Num_Subjects` columns.  We replaced missing information with 0 when the dtype was int, and with `None` otherwise.

Both dataframes were saved to `.csv` files: `df` to `MGP_clean.csv` and `ms` to `MScN_Author_clean.csv`.

### Joining `df` and `ms`

1. We then performed `df` left join `ms` on `MScNetID` to produce the dataframe `am`. We used a left join to retain all student/advisor data to help with feature enginnering.
2. We converted the `NaN`s in the numerical columns to -1s so those columns can be of type int.
3. There are 41037 rows in `am` with at least one students.  This will form the basis of our training/testing data for our model.